name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: alpine
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'

    - name: Test
      run: cd src/ && go test && cd ..

    - name: Build
      run: go build -o knights_tour src/main.go src/methods.go src/utils.go

    - name: Run
      run: ./knights_tour 16 0 0 wd
